name: sinlearn_mobile
description: "SinLearn - Sinhala Educational Assistant (Mobile + Web)"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1

  dio: ^5.4.0

  cupertino_icons: ^1.0.8

  # Localization support (English + Sinhala)
  easy_localization: ^3.0.1

  # State management (recommended for clean architecture)
  flutter_riverpod: ^2.5.1

  #create to route path
  go_router: ^14.2.1

  # Connectivity for detecting online/offline mode
  connectivity_plus: ^6.0.3

  # File picker for selecting PDF/images later
  file_picker: ^8.0.0

  # For HTTP API integration
  http: ^1.1.0

  # For voice recording (future use)
  audio_waveforms: ^1.2.0

  #For local storage
  shared_preferences: ^2.1.1
  # Secure storage for sensitive tokens
  flutter_secure_storage: ^8.0.0
  timeago: ^3.6.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  # Asset folders for localization, fonts, images, icons
  assets:
    - assets/languages/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  # Sinhala + English fonts (add actual font files later)
  fonts:
    - family: SinhalaFont
      fonts:
        - asset: assets/fonts/NotoSansSinhala-Regular.ttf
